server {
  listen 54170;
  listen [::]:54170;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.json;

  location = /healthz {
    default_type text/plain;
    try_files /healthz =404;
  }

  location = /index.json {
    default_type application/json;
    try_files /index.json =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
